[tool.poetry]
name = "sshfind"
version = "0.2.0"
description = "Search SSH configurations by host pattern"
authors = ["Samuel Garcia <13480326+samgrcia@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
rich = "^13.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0"

[tool.poetry.scripts]
sshfind = "sshfind:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
